spring:
  datasource:
    url: jdbc:postgresql://ep-lingering-sun-a4oc1exn.us-east-1.aws.neon.tech:5432/verceldb
    username: *******
    password: ********
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 1
      schema: lock

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
